name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GCP credentials.json
        run: |
          echo ${{ secrets.GCP_CREDENTIALS_JSON }} > credentials.json
          chmod 400 credentials.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.9

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Remove GCP credentials.json
        if: always()
        run: rm credentials.json
